const { chromium } = require('playwright');
const fs = require('fs');

(async () => {
    const browser = await chromium.launch();
    const context = await browser.newContext();
    const page = await context.newPage();

    console.log("Starting full functional tests for DiscuzX...");
    let report = "# DiscuzX Functional Test Report\n\n";

    try {
        const timestamp = Date.now();
        const username = `testuser_${timestamp}`;
        const email = `testuser_${timestamp}@example.com`;
        const password = 'Testpassword123!';

        // 1. User Registration
        console.log("Attempting User Registration...");
        await page.goto('http://127.0.0.1:8080/member.php?mod=register');
        await page.waitForLoadState('networkidle');

        // Discuz uses dynamic names for the username field. We find the text input preceding the password input.
        const inputs = await page.$$('input[type="text"]');
        const passwords = await page.$$('input[type="password"]');

        let usernameFilled = false;
        if (inputs.length > 0) {
            // First text input in registerform is usually username, except if email is first
            // We just try to fill the first few and see what happens.
            try { await inputs[0].fill(username); usernameFilled = true; } catch (e) {}
        }

        if (passwords.length >= 2) {
            await passwords[0].fill(password);
            await passwords[1].fill(password);
        }

        // Find email field
        let emailFilled = false;
        for (const input of inputs) {
            const name = await input.getAttribute('name');
            if (name && name.toLowerCase().includes('email')) {
                await input.fill(email);
                emailFilled = true;
                break;
            }
        }

        if (!emailFilled && inputs.length >= 2 && usernameFilled) {
            try { await inputs[1].fill(email); } catch (e) {}
        }

        await page.screenshot({ path: 'screenshot_01_reg_form.png' });

        const submitBtn = await page.$('button[name="regsubmit"]');
        if (submitBtn) {
            await submitBtn.click();
            await page.waitForTimeout(3000); // wait for redirect
        } else {
            console.log("Could not find regsubmit button");
        }

        await page.screenshot({ path: 'screenshot_02_reg_result.png' });

        report += `### 1. User Registration\n- **Status**: Checked\n- **Username**: ${username}\n- **Screenshots**: \`screenshot_01_reg_form.png\`, \`screenshot_02_reg_result.png\`\n\n`;

        // We will attempt to login with the default admin account instead for further tests
        console.log("Logging in as admin...");
        await page.goto('http://127.0.0.1:8080/member.php?mod=logging&action=login');
        await page.fill('input[name="username"]', 'admin');
        await page.fill('input[name="password"]', 'admin');
        const loginSubmitBtn = await page.$('button[name="loginsubmit"]');
        if (loginSubmitBtn) await loginSubmitBtn.click();
        await page.waitForTimeout(2000);

        // 2. Profile Changes
        console.log("Attempting User Profile changes...");
        await page.goto('http://127.0.0.1:8080/home.php?mod=spacecp');
        await page.screenshot({ path: 'screenshot_03_profile_before.png' });
        // Attempt a basic change
        const bioInput = await page.$('textarea[name="bio"]');
        if(bioInput) {
             await bioInput.fill('Updated bio from Playwright test');
             const saveBtn = await page.$('button[name="profilesubmit"]');
             if(saveBtn) await saveBtn.click();
             await page.waitForTimeout(1000);
        }
        await page.screenshot({ path: 'screenshot_04_profile_after.png' });
        report += `### 2. User Profile Changes\n- **Status**: Checked\n- **Screenshot**: \`screenshot_03_profile_before.png\`, \`screenshot_04_profile_after.png\`\n\n`;

        // 3. Posting Thread
        console.log("Attempting to post a thread...");
        await page.goto('http://127.0.0.1:8080/forum.php?mod=post&action=newthread&fid=2');
        await page.waitForTimeout(1000);

        const subjectInput = await page.$('input[name="subject"]');
        if (subjectInput) await subjectInput.fill('Test Thread by Playwright');

        const messageInput = await page.$('textarea[name="message"]');
        if (messageInput) await messageInput.fill('This is a test thread content generated by automated functional testing.');

        await page.screenshot({ path: 'screenshot_05_new_thread_form.png' });

        const postSubmitBtn = await page.$('button[name="topicsubmit"]');
        if (postSubmitBtn) {
            await postSubmitBtn.click();
            await page.waitForTimeout(2000);
        }
        await page.screenshot({ path: 'screenshot_06_new_thread_result.png' });
        report += `### 3. Posting Thread\n- **Status**: Checked\n- **Screenshot**: \`screenshot_05_new_thread_form.png\`, \`screenshot_06_new_thread_result.png\`\n\n`;

        // 4. Replying
        console.log("Attempting to reply to a thread...");
        await page.goto('http://127.0.0.1:8080/forum.php?mod=forumdisplay&fid=2');
        await page.waitForTimeout(1000);
        // Click the first thread
        const threads = await page.$$('a.s.xst');
        if (threads.length > 0) {
            await threads[0].click();
            await page.waitForTimeout(2000);

            const replyMessage = await page.$('textarea[name="message"]');
            if (replyMessage) await replyMessage.fill('This is an automated reply from Playwright.');

            await page.screenshot({ path: 'screenshot_07_reply_form.png' });

            const replySubmitBtn = await page.$('button[name="replysubmit"]');
            if(replySubmitBtn) {
                await replySubmitBtn.click();
                await page.waitForTimeout(2000);
            }
            await page.screenshot({ path: 'screenshot_08_reply_result.png' });
            report += `### 4. Replying to Thread\n- **Status**: Checked\n- **Screenshot**: \`screenshot_07_reply_form.png\`, \`screenshot_08_reply_result.png\`\n\n`;
        } else {
             report += `### 4. Replying to Thread\n- **Status**: Skipped (No threads found in fid=2)\n\n`;
        }

        // 5. Admin Panel
        console.log("Checking Admin Panel Access...");
        await page.goto('http://127.0.0.1:8080/admin.php');
        await page.waitForTimeout(1000);
        await page.screenshot({ path: 'screenshot_09_admin_login.png' });

        const adminPassInput = await page.$('input[name="admin_password"]');
        if(adminPassInput) {
            await adminPassInput.fill('admin');
            const adminSubmitBtn = await page.$('input[name="submit"]');
            if (adminSubmitBtn) await adminSubmitBtn.click();
            await page.waitForTimeout(3000);
        }
        await page.screenshot({ path: 'screenshot_10_admin_panel.png' });
        report += `### 5. Admin Panel Access\n- **Status**: Checked\n- **Screenshot**: \`screenshot_09_admin_login.png\`, \`screenshot_10_admin_panel.png\`\n\n`;

    } catch (error) {
        console.error("Test execution failed:", error);
        report += "## Error Encountered\n```\n" + error.message + "\n```\n\n";
    } finally {
        await browser.close();
        fs.writeFileSync('functional_test_report.md', report);
        console.log("Tests completed and report saved to functional_test_report.md");
    }
})();
