/**
 * Algolia Crawler Configuration — kuing.cjhb.site
 *
 * This file is pasted verbatim into the Algolia Crawler dashboard editor at:
 *   https://crawler.algolia.com/admin/crawlers/<crawler-id>/configuration/edit
 *
 * It is NOT executed locally. The Crawler runtime calls `new Crawler({...})`
 * with the configuration object defined here.
 *
 * Key settings:
 *   - appId / apiKey : Algolia application credentials (write key scoped to crawler)
 *   - sitemaps       : entry point — the sitemap at /sitemap.xml is generated by
 *                      source/child/cron/cron_sitemap.php (runs as a scheduled cron task);
 *                      only forum.php?mod=viewthread thread pages are indexed
 *   - actions        : one action that extracts per-post records from table.plhin rows
 *   - initialIndexSettings : ranking, facets, snippet, and language settings for the "kuing" index
 *
 * To update the crawler schedule or index settings, edit this file and paste the
 * updated content into the dashboard editor, then save and re-run the crawler.
 */

new Crawler({
    appId: "YOUR_APP_ID",       // Algolia Application ID (find in dashboard → Settings → API Keys)
    apiKey: "YOUR_CRAWLER_API_KEY", // Crawler write API key (not the search-only key)
    maxUrls: null,
    indexPrefix: "",
    rateLimit: 8,
    ignoreQueryParams: ["extra", "mobile", "authorid", "highlight", "ordertype"],
    schedule: "every 1 day at 12:51 pm",
    maxDepth: 10,
    linkExtractor: ({ $, url, defaultExtractor }) => {
        if (url.href == "https://kuing.cjhb.site/sitemap.xml") {
            return defaultExtractor().map((a) =>
                a.replace(
                    /^https:\/\/kuing.cjhb.site\/thread-(\d+)-(\d+)-\d+\.html$/,
                    (m, p1, p2) =>
                        p2 == "1"
                            ? "https://kuing.cjhb.site/forum.php?mod=viewthread&tid=" + p1
                            : "https://kuing.cjhb.site/forum.php?mod=viewthread&tid=" +
                            p1 +
                            "&page=" +
                            p2,
                ),
            );
        }
        return [];
    },
    ignoreCanonicalTo: true,
    actions: [
        {
            indexName: "kuing",
            pathsToMatch: ["**"],
            recordExtractor: ({ url, $, contentLength, fileType }) => {
                const records = [];
                $("table.plhin")
                    .get()
                    .map(function (a) {
                        // Strip quoted blocks so replies that only quote someone
                        // else are not indexed as original content.
                        //
                        // The attribution line is what we match on, and it is
                        // emitted from the [size=2] bbcode that the editor wraps
                        // around its "X wrote:" header. Commit 515cdbea8
                        // ("refactor(html): replace font output with styled
                        // spans", 2026-08-22) rewrote function_discuzcode.php to
                        // emit <span style="..."> instead of the deprecated
                        // <font>, so the header changed from
                        // <font size="2"> to <span style="font-size:small">.
                        // The old filter matched nothing after that, .remove()
                        // became a no-op, and every quote got indexed.
                        //
                        // :first-child rather than a bare descendant match: the
                        // attribution is emitted first, so anchoring on it stops
                        // a quote being stripped just because the quoted text
                        // happens to contain some other small-font span. A child
                        // combinator would express this too, but the crawler
                        // runtime supplies Cheerio, whose .has() handling of a
                        // leading ">" is not dependable across versions.
                        //
                        // No <font size=2> fallback: the parser no longer emits
                        // it, and a scan of pre_forum_post found 0 stored
                        // messages containing a raw <font size=2> inside a
                        // quote-bearing post (the 37 hits are all inside [code]
                        // blocks quoting Discuz's own source), so the extra
                        // selector only risks false positives.
                        //
                        // Coverage, measured on pre_forum_post (2026-09-26,
                        // after a one-off normalisation moved legacy
                        // end-attributions to the front):
                        //   7,264 of 9,030 quote posts have the attribution
                        //     immediately after [quote]   -> stripped
                        //       74 have it later in the quote -> deliberately not
                        //    1,692 have no attribution at all  -> not stripped
                        $(a)
                            .find("div.quote > blockquote")
                            .has('span[style*="font-size:small"]:first-child')
                            .remove();
                        const content = $(a).find("td.t_f").text().trim();
                        if (content != "") {
                            records.push({
                                objectID: $(a).prop("id").slice(3),
                                date: $(a).find('em[id^="authorposton"]').text(),
                                pid: parseInt($(a).prop("id").slice(3)),
                                title: $("#thread_subject").text(),
                                author: $(a).find(".authi a.xw1").text(),
                                forum: $('div.z a[href^="forum-"]')
                                    .get()
                                    .map(
                                        (x) =>
                                            $(x)
                                                .attr("href")
                                                .match(/forum-(\d+)/)[1],
                                    ),
                                keywords: $('meta[name="keywords"]').prop("content").split(","),
                                totalposts: $("td.t_f").length,
                                content: content,
                            });
                        }
                    });
                return records;
            },
        },
    ],
    sitemaps: ["https://kuing.cjhb.site/sitemap.xml"],
    initialIndexSettings: {
        kuing: {
            advancedSyntax: true,
            typoTolerance: false,
            alternativesAsExact: ["ignorePlurals"],
            allowTyposOnNumericTokens: false,
            attributeCriteriaComputedByMinProximity: true,
            attributesToSnippet: ["content:30"],
            attributesForFaceting: ["forum", "author", "keywords"],
            customRanking: ["desc(pid)"],
            distinct: 1,
            highlightPostTag: "</span>",
            highlightPreTag: '<span class="algolia-docsearch-suggestion--highlight">',
            ignorePlurals: true,
            minProximity: 1,
            minWordSizefor1Typo: 3,
            minWordSizefor2Typos: 7,
            separatorsToIndex: "!#()[]{}*+-_一,:;<>?@/\\^|%&~§`'''""†‡",
            ranking: [
                "words",
                "filters",
                "typo",
                "attribute",
                "proximity",
                "exact",
                "custom",
            ],
            queryLanguages: ["zh", "en"],
            removeWordsIfNoResults: "allOptional",
            searchableAttributes: [
                "unordered(title)",
                "unordered(keywords)",
                "unordered(content)",
            ],
        },
    },
    safetyChecks: { beforeIndexPublishing: { maxLostRecordsPercentage: 10 } },
});
